### PR TITLE
Added status bar and status bar fields to both gui.css and xp.cs

### PR DESCRIPTION
**Pull request by Andreymazepas**
Hello, I tried to recreate the style of footer you would see on the task manager for both systems.
image
image

### CODE REVIEW

**Comment by Andreymazepas** [comment]
Should I add the documentation before the PR?

**Comment by botoxparty** [comment]
wow! that looks great! 

Yes if you don't mind updating the documentation to include this feature in the Window section i'll be able to merge this 👍

**Comment by Andreymazepas** [comment]
I had some free time and decided to take a look at the Windows Interface Guidelines from 1995, incredible stuff! 
I found that the correct name for this section is status-bar, I already corrected the name and added it under the window-body section in the docs :)

**Comment by botoxparty** [comment]
Awesome! Thanks so much for this.

Also saw that you have created a PR on 98.css as well. ✨

**Pull request merged**
